[tool.poetry]
name = "novum_api_client"
version = "1.0.1"
description = "This library contains the basic API functions for Novum Service Center."
authors = ["Leonardo <l.biz@novum-engineering.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
requests = "^2.28.2"